"""
Agent 安全模块

提供 RBAC 权限控制、敏感操作验证、风险评估等功能
"""
from .rbac import (
    Permission,
    Role,
    ResourceType,
    OperationType,
    RoleDefinition,
    PermissionSet,
    ResourcePermission,
    RBACManager,
    RoleAssignment,
    get_rbac_manager,
    require_permission,
    require_role,
    require_admin,
    check_permission,
    RoleInheritance,
    PermissionInheritance,
    InheritanceResolver,
)

from .verification import (
    SensitiveOperationClassifier,
    SensitivityLevel,
    SensitiveOperation,
    VerificationSession,
    VerificationSessionManager,
    VerificationType,
    VerificationStatus,
    VerificationAPI,
    VerificationRequest,
    VerificationResponse,
    get_verification_api,
)

from .risk import (
    RiskRule,
    RiskRuleEngine,
    RiskFactor,
    RiskCategory,
    RiskScorer,
    RiskScore,
    RiskLevel,
    RiskAlertManager,
    RiskAlert,
    AlertSeverity,
    get_alert_manager,
)

__all__ = [
    "Permission",
    "Role",
    "ResourceType",
    "OperationType",
    "RoleDefinition",
    "PermissionSet",
    "ResourcePermission",
    "RBACManager",
    "RoleAssignment",
    "get_rbac_manager",
    "require_permission",
    "require_role",
    "require_admin",
    "check_permission",
    "RoleInheritance",
    "PermissionInheritance",
    "InheritanceResolver",
    "SensitiveOperationClassifier",
    "SensitivityLevel",
    "SensitiveOperation",
    "VerificationSession",
    "VerificationSessionManager",
    "VerificationType",
    "VerificationStatus",
    "VerificationAPI",
    "VerificationRequest",
    "VerificationResponse",
    "get_verification_api",
    "RiskRule",
    "RiskRuleEngine",
    "RiskFactor",
    "RiskCategory",
    "RiskScorer",
    "RiskScore",
    "RiskLevel",
    "RiskAlertManager",
    "RiskAlert",
    "AlertSeverity",
    "get_alert_manager",
]
